// Question bank for QuickQuiz
// Each question: { id, category, text, options: [], correctIndex, difficulty }

const QUESTION_CATEGORIES = [
  {
    id: 'science',
    name: 'Science',
    description: 'Physics, biology, astronomy and how the universe works.',
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    description: 'Atoms, reactions, elements and everyday substances.',
  },
  {
    id: 'history',
    name: 'History',
    description: 'Civilizations, events and people that shaped our world.',
  },
  {
    id: 'geography',
    name: 'Geography',
    description: 'Countries, landforms, climates and maps of Earth.',
  },
  {
    id: 'religion',
    name: 'Religion',
    description: 'Beliefs, practices and texts from major religions.',
  },
  {
    id: 'general',
    name: 'Earth & World',
    description: 'Mixed facts about our planet and human civilization.',
  },
];

const QUESTION_BANK = [
  // Science
  {
    id: 'science-1',
    category: 'science',
    text: 'What is the basic unit of life in all known organisms?',
    options: ['Atom', 'Cell', 'Molecule', 'Tissue'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'science-2',
    category: 'science',
    text: 'Which part of the cell contains the genetic material (DNA) in eukaryotes?',
    options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Cell membrane'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'science-3',
    category: 'science',
    text: 'What force keeps planets in orbit around the Sun?',
    options: ['Magnetism', 'Friction', 'Gravity', 'Electric force'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'science-4',
    category: 'science',
    text: 'Light travels fastest in which medium?',
    options: ['Diamond', 'Water', 'Glass', 'Vacuum'],
    correctIndex: 3,
    difficulty: 'medium',
  },
  {
    id: 'science-5',
    category: 'science',
    text: 'Which scientist proposed the three laws of motion?',
    options: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Niels Bohr'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'science-6',
    category: 'science',
    text: 'What gas do plants primarily absorb from the atmosphere for photosynthesis?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'science-7',
    category: 'science',
    text: 'Which part of the human brain is mainly responsible for balance and coordination?',
    options: ['Cerebrum', 'Cerebellum', 'Brain stem', 'Thalamus'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'science-8',
    category: 'science',
    text: 'What is the approximate age of the universe according to current scientific estimates?',
    options: ['4.5 billion years', '13.8 billion years', '1 trillion years', '500 million years'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'science-9',
    category: 'science',
    text: 'What term describes an organism that can make its own food using light or chemical energy?',
    options: ['Heterotroph', 'Producer', 'Consumer', 'Predator'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'science-10',
    category: 'science',
    text: 'What is the main gas responsible for the greenhouse effect on modern Earth?',
    options: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'science-11',
    category: 'science',
    text: 'Which phenomenon explains why we see lightning before we hear thunder?',
    options: [
      'Light travels faster than sound',
      'Thunder is absorbed by clouds',
      'Lightning is closer to Earth',
      'Air blocks sound completely',
    ],
    correctIndex: 0,
    difficulty: 'easy',
  },
  {
    id: 'science-12',
    category: 'science',
    text: 'Which of these is NOT a renewable energy source?',
    options: ['Solar', 'Wind', 'Coal', 'Hydroelectric'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'science-13',
    category: 'science',
    text: 'Which layer of the atmosphere contains the ozone layer that absorbs most UV radiation?',
    options: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'science-14',
    category: 'science',
    text: 'What is the main function of red blood cells?',
    options: [
      'Fighting infections',
      'Carrying oxygen',
      'Clotting blood',
      'Producing hormones',
    ],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'science-15',
    category: 'science',
    text: 'Which planet in our solar system has the largest number of known moons?',
    options: ['Earth', 'Mars', 'Jupiter', 'Mercury'],
    correctIndex: 2,
    difficulty: 'medium',
  },

  // Chemistry
  {
    id: 'chem-1',
    category: 'chemistry',
    text: 'What is the chemical symbol for gold?',
    options: ['Gd', 'Au', 'Ag', 'Go'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-2',
    category: 'chemistry',
    text: 'Water (H₂O) is an example of which type of compound?',
    options: ['Ionic compound', 'Covalent compound', 'Metallic compound', 'Alloy'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-3',
    category: 'chemistry',
    text: 'What is the pH of a neutral solution at room temperature?',
    options: ['0', '3', '7', '14'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'chem-4',
    category: 'chemistry',
    text: 'Which gas is commonly known as laughing gas and used in anesthesia?',
    options: ['Nitrous oxide (N₂O)', 'Carbon monoxide (CO)', 'Ozone (O₃)', 'Nitrogen (N₂)'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'chem-5',
    category: 'chemistry',
    text: 'Which subatomic particle determines the atomic number of an element?',
    options: ['Neutron', 'Electron', 'Proton', 'Positron'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'chem-6',
    category: 'chemistry',
    text: 'Table salt used in food is mainly composed of which compound?',
    options: ['Potassium chloride', 'Sodium chloride', 'Calcium carbonate', 'Magnesium sulfate'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-7',
    category: 'chemistry',
    text: 'What term describes a substance that speeds up a chemical reaction without being consumed?',
    options: ['Reactant', 'Solvent', 'Catalyst', 'Inhibitor'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'chem-8',
    category: 'chemistry',
    text: 'Which bond is formed by sharing a pair of electrons between two atoms?',
    options: ['Ionic bond', 'Covalent bond', 'Hydrogen bond', 'Metallic bond'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-9',
    category: 'chemistry',
    text: 'Which gas is responsible for the characteristic smell of rotten eggs?',
    options: ['Methane (CH₄)', 'Hydrogen sulfide (H₂S)', 'Ammonia (NH₃)', 'Carbon dioxide (CO₂)'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'chem-10',
    category: 'chemistry',
    text: 'What name is given to the horizontal rows in the periodic table?',
    options: ['Groups', 'Periods', 'Series', 'Blocks'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-11',
    category: 'chemistry',
    text: 'Which acid is commonly found in car batteries?',
    options: ['Hydrochloric acid', 'Sulfuric acid', 'Nitric acid', 'Acetic acid'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'chem-12',
    category: 'chemistry',
    text: 'What is the lightest element in the periodic table?',
    options: ['Helium', 'Hydrogen', 'Lithium', 'Neon'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'chem-13',
    category: 'chemistry',
    text: 'Which family of elements is known as the noble gases?',
    options: ['Group 1', 'Group 2', 'Group 17', 'Group 18'],
    correctIndex: 3,
    difficulty: 'medium',
  },
  {
    id: 'chem-14',
    category: 'chemistry',
    text: 'Which process describes the transition from a liquid to a gas at the surface?',
    options: ['Condensation', 'Freezing', 'Evaporation', 'Sublimation'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'chem-15',
    category: 'chemistry',
    text: 'What is the approximate percentage of nitrogen gas in Earth’s atmosphere?',
    options: ['21%', '50%', '78%', '90%'],
    correctIndex: 2,
    difficulty: 'medium',
  },

  // History
  {
    id: 'hist-1',
    category: 'history',
    text: 'Which ancient civilization built the pyramids at Giza?',
    options: ['Ancient Greece', 'Ancient Egypt', 'Maya civilization', 'Roman Empire'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'hist-2',
    category: 'history',
    text: 'Who was the first President of the United States of America?',
    options: [
      'George Washington',
      'Abraham Lincoln',
      'Thomas Jefferson',
      'Benjamin Franklin',
    ],
    correctIndex: 0,
    difficulty: 'easy',
  },
  {
    id: 'hist-3',
    category: 'history',
    text: 'In which year did World War II end?',
    options: ['1918', '1939', '1945', '1965'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'hist-4',
    category: 'history',
    text: 'The Silk Road was a trade route that primarily connected China with which region?',
    options: ['Sub-Saharan Africa', 'Europe and the Mediterranean', 'Australia', 'The Arctic'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'hist-5',
    category: 'history',
    text: 'Which empire was ruled by Genghis Khan?',
    options: ['Roman Empire', 'Ottoman Empire', 'Mongol Empire', 'Persian Empire'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'hist-6',
    category: 'history',
    text: 'Which revolution led to the fall of the monarchy in France in 1789?',
    options: [
      'American Revolution',
      'Russian Revolution',
      'French Revolution',
      'Industrial Revolution',
    ],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'hist-7',
    category: 'history',
    text: 'Which city was divided by a wall between 1961 and 1989, symbolizing the Cold War?',
    options: ['Berlin', 'Moscow', 'London', 'Tokyo'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'hist-8',
    category: 'history',
    text: 'Who was known as the “Mahatma” and led India’s non-violent independence movement?',
    options: [
      'Subhas Chandra Bose',
      'Jawaharlal Nehru',
      'Mahatma Gandhi',
      'B. R. Ambedkar',
    ],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'hist-9',
    category: 'history',
    text: 'Which empire built the famous roadway called the “Appian Way”?',
    options: ['Greek Empire', 'Roman Empire', 'Byzantine Empire', 'Inca Empire'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'hist-10',
    category: 'history',
    text: 'What was the primary purpose of the Great Wall of China?',
    options: [
      'Transportation',
      'Flood control',
      'Defense against invasions',
      'Trade taxation',
    ],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'hist-11',
    category: 'history',
    text: 'Which pandemic in the 14th century killed an estimated one-third of Europe’s population?',
    options: ['Spanish flu', 'Black Death', 'Cholera outbreak', 'COVID-19'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'hist-12',
    category: 'history',
    text: 'Who was the first human to travel into outer space?',
    options: [
      'Neil Armstrong',
      'Yuri Gagarin',
      'Valentina Tereshkova',
      'Buzz Aldrin',
    ],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'hist-13',
    category: 'history',
    text: 'Which document, signed in 1215, limited the powers of the English king and is seen as a step toward constitutional law?',
    options: [
      'Bill of Rights',
      'Declaration of Independence',
      'Magna Carta',
      'Treaty of Versailles',
    ],
    correctIndex: 2,
    difficulty: 'hard',
  },
  {
    id: 'hist-14',
    category: 'history',
    text: 'The ancient city of Machu Picchu is located in which modern-day country?',
    options: ['Mexico', 'Peru', 'Chile', 'Brazil'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'hist-15',
    category: 'history',
    text: 'What was the name of the trade network that connected West Africa with North Africa, mainly through the Sahara Desert?',
    options: [
      'Trans-Saharan trade routes',
      'Silk Road',
      'Amber Road',
      'Spice Route',
    ],
    correctIndex: 0,
    difficulty: 'hard',
  },

  // Geography
  {
    id: 'geo-1',
    category: 'geography',
    text: 'What is the largest continent on Earth by land area?',
    options: ['Africa', 'Asia', 'North America', 'Europe'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'geo-2',
    category: 'geography',
    text: 'Which river is the longest in the world by most modern measurements?',
    options: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'geo-3',
    category: 'geography',
    text: 'Which country has the largest population in the world?',
    options: ['India', 'China', 'United States', 'Indonesia'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'geo-4',
    category: 'geography',
    text: 'Mount Everest lies on the border of Nepal and which other country?',
    options: ['India', 'China (Tibet)', 'Bhutan', 'Pakistan'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'geo-5',
    category: 'geography',
    text: 'Which ocean is the smallest by surface area?',
    options: ['Indian Ocean', 'Atlantic Ocean', 'Arctic Ocean', 'Pacific Ocean'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'geo-6',
    category: 'geography',
    text: 'What is the capital city of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'geo-7',
    category: 'geography',
    text: 'Which desert is the largest hot desert in the world?',
    options: ['Gobi', 'Sahara', 'Kalahari', 'Atacama'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'geo-8',
    category: 'geography',
    text: 'Which country is both in Europe and Asia, straddling the Bosporus Strait?',
    options: ['Russia', 'Turkey', 'Kazakhstan', 'Ukraine'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'geo-9',
    category: 'geography',
    text: 'Which line of latitude is also known as the Equator?',
    options: ['0°', '23.5°N', '66.5°N', '90°N'],
    correctIndex: 0,
    difficulty: 'easy',
  },
  {
    id: 'geo-10',
    category: 'geography',
    text: 'Which South American country is landlocked?',
    options: ['Peru', 'Chile', 'Bolivia', 'Ecuador'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'geo-11',
    category: 'geography',
    text: 'Which African lake is the source of the White Nile and is one of the largest lakes in the world?',
    options: ['Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'Lake Chad'],
    correctIndex: 0,
    difficulty: 'hard',
  },
  {
    id: 'geo-12',
    category: 'geography',
    text: 'What is the term for a narrow strip of land connecting two larger land areas, often with water on both sides?',
    options: ['Peninsula', 'Isthmus', 'Archipelago', 'Delta'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'geo-13',
    category: 'geography',
    text: 'Which country is famous for its fjords, long narrow inlets with steep sides?',
    options: ['Norway', 'Italy', 'Japan', 'Canada'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'geo-14',
    category: 'geography',
    text: 'Which city is known as the highest capital city in the world (by elevation above sea level)?',
    options: ['La Paz, Bolivia', 'Quito, Ecuador', 'Lhasa, Tibet', 'Kathmandu, Nepal'],
    correctIndex: 0,
    difficulty: 'hard',
  },
  {
    id: 'geo-15',
    category: 'geography',
    text: 'Which country has coastlines on both the Atlantic and Indian Oceans?',
    options: ['South Africa', 'Brazil', 'India', 'Mexico'],
    correctIndex: 0,
    difficulty: 'medium',
  },

  // Religion
  {
    id: 'rel-1',
    category: 'religion',
    text: 'Which religion considers the Quran (Koran) as its central holy book?',
    options: ['Christianity', 'Islam', 'Hinduism', 'Buddhism'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'rel-2',
    category: 'religion',
    text: 'In Christianity, what is the name of the collection of sacred scriptures?',
    options: ['Torah', 'Vedas', 'Bible', 'Tripitaka'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'rel-3',
    category: 'religion',
    text: 'Which religion is most closely associated with the concept of karma and reincarnation in South Asia?',
    options: ['Islam', 'Judaism', 'Hinduism', 'Sikhism'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'rel-4',
    category: 'religion',
    text: 'Buddhism originated in which modern-day country?',
    options: ['China', 'India', 'Japan', 'Thailand'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'rel-5',
    category: 'religion',
    text: 'The Torah is a central text in which religion?',
    options: ['Judaism', 'Christianity', 'Islam', 'Zoroastrianism'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'rel-6',
    category: 'religion',
    text: 'The Kaaba, a cube-shaped building in Mecca, is a sacred site for followers of which religion?',
    options: ['Hinduism', 'Islam', 'Christianity', 'Buddhism'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'rel-7',
    category: 'religion',
    text: 'Sikhism was founded in the Punjab region by which spiritual teacher?',
    options: ['Guru Gobind Singh', 'Guru Nanak', 'Adi Shankaracharya', 'Laozi'],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'rel-8',
    category: 'religion',
    text: 'In many Indigenous African religions, what role do ancestors typically play?',
    options: [
      'They are ignored after death',
      'They act as spiritual guardians and intermediaries',
      'They are considered evil spirits',
      'They must be forgotten to break curses',
    ],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'rel-9',
    category: 'religion',
    text: 'Which religion uses the Eightfold Path as a guide to ethical and mental development?',
    options: ['Christianity', 'Judaism', 'Buddhism', 'Islam'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'rel-10',
    category: 'religion',
    text: 'The festival of Diwali, celebrated with lamps and fireworks, is strongly associated with which religion?',
    options: ['Hinduism', 'Islam', 'Christianity', 'Baha’i Faith'],
    correctIndex: 0,
    difficulty: 'easy',
  },
  {
    id: 'rel-11',
    category: 'religion',
    text: 'In which religion is the concept of “halal” used to describe what is permissible?',
    options: ['Judaism', 'Christianity', 'Islam', 'Hinduism'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'rel-12',
    category: 'religion',
    text: 'Which religious tradition regards the Ganges River as especially sacred?',
    options: ['Christianity', 'Hinduism', 'Buddhism', 'Shinto'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'rel-13',
    category: 'religion',
    text: 'The term “Torii gate” is most closely associated with which Japanese religion?',
    options: ['Shinto', 'Buddhism', 'Christianity', 'Confucianism'],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'rel-14',
    category: 'religion',
    text: 'The “Five Pillars” are core practices in which religion?',
    options: ['Islam', 'Christianity', 'Judaism', 'Hinduism'],
    correctIndex: 0,
    difficulty: 'easy',
  },
  {
    id: 'rel-15',
    category: 'religion',
    text: 'Which religious tradition places strong emphasis on the teachings of Confucius about ethics and social harmony?',
    options: ['Confucianism', 'Taoism', 'Buddhism', 'Zoroastrianism'],
    correctIndex: 0,
    difficulty: 'hard',
  },

  // General Earth & World (mixed)
  {
    id: 'gen-1',
    category: 'general',
    text: 'Approximately what fraction of Earth’s surface is covered by oceans?',
    options: ['About one-quarter', 'About one-half', 'About two-thirds', 'Almost all of it'],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'gen-2',
    category: 'general',
    text: 'Which layer of Earth lies directly below the crust?',
    options: ['Inner core', 'Mantle', 'Outer core', 'Asthenosphere only'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'gen-3',
    category: 'general',
    text: 'Which human-made structure can be seen from low Earth orbit but not typically from the Moon with the naked eye?',
    options: [
      'Great Wall of China',
      'Eiffel Tower',
      'Statue of Liberty',
      'Pyramids of Giza',
    ],
    correctIndex: 0,
    difficulty: 'medium',
  },
  {
    id: 'gen-4',
    category: 'general',
    text: 'Which gas makes up most of Earth’s atmosphere?',
    options: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'gen-5',
    category: 'general',
    text: 'Which world organization was founded after World War II to promote international peace and cooperation?',
    options: [
      'League of Nations',
      'European Union',
      'United Nations',
      'World Trade Organization',
    ],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'gen-6',
    category: 'general',
    text: 'Which process drives the movement of Earth’s tectonic plates?',
    options: [
      'Ocean tides',
      'Convection in the mantle',
      'Wind patterns',
      'Magnetic storms from the Sun',
    ],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'gen-7',
    category: 'general',
    text: 'Which civilization built a complex road network across the Andes Mountains in South America?',
    options: ['Maya', 'Inca', 'Aztec', 'Olmec'],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'gen-8',
    category: 'general',
    text: 'What is the term for a community of living organisms interacting with their physical environment?',
    options: ['Biosphere', 'Ecosystem', 'Habitat', 'Biome'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'gen-9',
    category: 'general',
    text: 'Which international agreement, adopted in 2015, focuses on limiting global warming?',
    options: [
      'Kyoto Protocol',
      'Paris Agreement',
      'Montreal Protocol',
      'Geneva Convention',
    ],
    correctIndex: 1,
    difficulty: 'medium',
  },
  {
    id: 'gen-10',
    category: 'general',
    text: 'What is biodiversity?',
    options: [
      'The speed of evolution',
      'The total number of humans on Earth',
      'The variety of life in a particular habitat or on Earth as a whole',
      'The strength of an ecosystem to resist change',
    ],
    correctIndex: 2,
    difficulty: 'easy',
  },
  {
    id: 'gen-11',
    category: 'general',
    text: 'Which energy source is considered renewable?',
    options: ['Coal', 'Oil', 'Natural gas', 'Solar power'],
    correctIndex: 3,
    difficulty: 'easy',
  },
  {
    id: 'gen-12',
    category: 'general',
    text: 'Which term describes the long-term average of weather patterns in a region?',
    options: ['Forecast', 'Climate', 'Season', 'Front'],
    correctIndex: 1,
    difficulty: 'easy',
  },
  {
    id: 'gen-13',
    category: 'general',
    text: 'Which of the following is a major monotheistic religion that originated in the Middle East?',
    options: ['Hinduism', 'Shinto', 'Judaism', 'Confucianism'],
    correctIndex: 2,
    difficulty: 'medium',
  },
  {
    id: 'gen-14',
    category: 'general',
    text: 'Which ocean current strongly influences the climate of Western Europe by bringing warm water from the tropics?',
    options: [
      'California Current',
      'Gulf Stream',
      'Humboldt Current',
      'Kuroshio Current',
    ],
    correctIndex: 1,
    difficulty: 'hard',
  },
  {
    id: 'gen-15',
    category: 'general',
    text: 'Which instrument is commonly used to measure earthquakes?',
    options: ['Thermometer', 'Barometer', 'Seismograph', 'Hygrometer'],
    correctIndex: 2,
    difficulty: 'easy',
  },
];

